// scripts/generate-storage-seed.ts
// CLI: bun scripts/generate-storage-seed.ts
//
// uploads/ klasörünü tarayip storage_assets icin SQL seed olusturur.
// Cikti: src/db/seed/sql/008_storage_assets_uploads.sql
//
// Mantik:
// - INSERT IGNORE ile yazar (007'deki manuel tanimli kayitlarla
//   bucket+path UNIQUE constraint'i sayesinde catismaz, otomatik atlar)
// - id deterministik (path hash'inden uretilir) — her run ayni id'yi verir
// - dosya degisiklikleri commit'lendiginde aynisi canliya gider

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const root = path.resolve(process.cwd(), 'uploads');
// SON seed olarak calisir (en buyuk numara). Diger seed'lerden sonra
// eksik kalan upload dosyalarini INSERT IGNORE ile ekler.
const outFile = path.resolve(
  process.cwd(),
  'src',
  'db',
  'seed',
  'sql',
  '999_storage_assets_uploads.sql',
);
const urlPrefix = '/uploads/';

const MIME_BY_EXT: Record<string, string> = {
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.gif': 'image/gif',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.bmp': 'image/bmp',
  '.tif': 'image/tiff',
  '.tiff': 'image/tiff',
  '.avif': 'image/avif',
  '.pdf': 'application/pdf',
  '.mp4': 'video/mp4',
  '.webm': 'video/webm',
  '.mov': 'video/quicktime',
  '.mp3': 'audio/mpeg',
  '.zip': 'application/zip',
  '.json': 'application/json',
  '.txt': 'text/plain',
};

function mimeFromExt(ext: string): string {
  return MIME_BY_EXT[ext.toLowerCase()] ?? 'application/octet-stream';
}

function* walk(dir: string, base: string): Generator<{ abs: string; rel: string }> {
  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const ent of entries) {
    const abs = path.join(dir, ent.name);
    if (ent.isDirectory()) {
      if (ent.name === 'db_snapshots') continue;
      yield* walk(abs, base);
    } else if (ent.isFile()) {
      if (ent.name.startsWith('.')) continue;
      const rel = path.relative(base, abs).replaceAll(path.sep, '/');
      yield { abs, rel };
    }
  }
}

// Path'ten deterministik UUIDv5-benzeri 36 karakter id uret
function deterministicId(rel: string): string {
  const h = crypto.createHash('sha1').update(`storage:${rel}`).digest('hex');
  return [
    h.slice(0, 8),
    h.slice(8, 12),
    '4' + h.slice(13, 16),
    '8' + h.slice(17, 20),
    h.slice(20, 32),
  ].join('-');
}

function sqlEscape(v: string): string {
  return v.replaceAll("\\", "\\\\").replaceAll("'", "''");
}

function main() {
  if (!fs.existsSync(root)) {
    console.error('uploads root not found:', root);
    process.exit(1);
  }

  const rows: string[] = [];
  let count = 0;

  for (const file of walk(root, root)) {
    const stat = fs.statSync(file.abs);
    const ext = path.extname(file.abs);
    const folder = path.dirname(file.rel);
    const id = deterministicId(file.rel);
    const name = path.basename(file.abs);
    const mime = mimeFromExt(ext);

    const folderSql = folder === '.' ? 'NULL' : `'${sqlEscape(folder)}'`;
    rows.push(
      `('${id}','${sqlEscape(name)}','default','${sqlEscape(file.rel)}',${folderSql},'${mime}',${stat.size},'${urlPrefix}${sqlEscape(file.rel)}','local','${sqlEscape(file.rel)}')`,
    );
    count += 1;
  }

  rows.sort();

  const header = `-- =============================================================
-- 999_storage_assets_uploads.sql
-- AUTO-GENERATED by scripts/generate-storage-seed.ts. DO NOT EDIT.
-- Diskteki uploads/ klasorunun storage_assets'e kayit edilmesini saglar.
-- En son seed olarak calisir; diger seed'lerin (007, 121, 145, ...) yazdigi
-- kayitlarla bucket+path UNIQUE constraint'i sayesinde catismaz (INSERT IGNORE).
--
-- Yeni dosya eklediginizde:
--   bun run storage:generate-seed
-- ile bu dosya yeniden uretilir, commit edilir, canliya tasinir.
-- =============================================================

SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

`;

  if (rows.length === 0) {
    fs.writeFileSync(outFile, `${header}-- No files found in uploads/\n`);
    console.log(`No files in ${root}`);
    return;
  }

  const body = `INSERT IGNORE INTO \`storage_assets\`
  (\`id\`, \`name\`, \`bucket\`, \`path\`, \`folder\`, \`mime\`, \`size\`, \`url\`, \`provider\`, \`provider_public_id\`)
VALUES
  ${rows.join(',\n  ')};
`;

  fs.writeFileSync(outFile, header + body);
  console.log(`Generated ${count} entries → ${path.relative(process.cwd(), outFile)}`);
}

main();
