SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO `popups`
  (`id`, `uuid`, `type`, `title`, `content`, `background_color`, `text_color`, `button_text`, `button_color`, `button_hover_color`, `button_text_color`, `link_url`, `link_target`, `target_paths`, `image_url`, `image_asset_id`, `alt`, `text_behavior`, `scroll_speed`, `closeable`, `delay_seconds`, `display_frequency`, `is_active`, `display_order`, `start_at`, `end_at`)
VALUES
  (
    1,
    '99999999-9999-4999-8999-999999999991',
    'topbar',
    'Toplu satış planlamasını erkenden başlatın',
    'Yeni sezon için bayi, kooperatif ve kurumsal taleplerinizi toplu satış ekranından operasyon ekibine iletin.',
    '#17352f',
    '#f5f1e8',
    'Toplu Satışa Git',
    '#f0b429',
    '#d9980b',
    '#17352f',
    '/toplu-satis',
    '_self',
    '["/","/toplu-satis","/urunler","/urunler/*"]',
    NULL,
    NULL,
    NULL,
    'marquee',
    72,
    1,
    0,
    'daily',
    1,
    1,
    NULL,
    NULL
  ),
  (
    2,
    '99999999-9999-4999-8999-999999999992',
    'sidebar_top',
    'Bilgi bankasında yeni teknik içerikler',
    'Fide dikimi, sera geçişi ve ürün kararlarını destekleyen güncel rehberleri bilgi bankasında inceleyin.',
    '#f4efe4',
    '#17352f',
    'Bilgi Bankasını Aç',
    '#17352f',
    '#245247',
    '#ffffff',
    '/bilgi-bankasi',
    '_self',
    '["/bilgi-bankasi","/bilgi-bankasi/*","/ekim-rehberi","/ekim-rehberi/*"]',
    '/uploads/popups/popup-catalog-01.jpg',
    NULL,
    'Bilgi bankası popup görseli',
    'static',
    60,
    1,
    2,
    'always',
    1,
    2,
    NULL,
    NULL
  ),
  (
    3,
    '99999999-9999-4999-8999-999999999993',
    'sidebar_center',
    'Bayi ağı görünürlüğünü inceleyin',
    'Bölgesel dağıtım yapımızı ve saha erişim modelimizi bayi ağı sayfasında görüntüleyin.',
    '#ffffff',
    '#1f2937',
    'Bayi Ağını Aç',
    '#1f6f5f',
    '#184f45',
    '#ffffff',
    '/bayi-agi',
    '_self',
    '["/","/bayi-agi","/bayi-agi/*","/hakkimizda"]',
    '/uploads/popups/popup-references-01.jpg',
    NULL,
    'Bayi ağı popup görseli',
    'static',
    60,
    1,
    1,
    'once',
    1,
    3,
    NULL,
    NULL
  )
ON DUPLICATE KEY UPDATE
  `uuid` = VALUES(`uuid`),
  `type` = VALUES(`type`),
  `title` = VALUES(`title`),
  `content` = VALUES(`content`),
  `background_color` = VALUES(`background_color`),
  `text_color` = VALUES(`text_color`),
  `button_text` = VALUES(`button_text`),
  `button_color` = VALUES(`button_color`),
  `button_hover_color` = VALUES(`button_hover_color`),
  `button_text_color` = VALUES(`button_text_color`),
  `link_url` = VALUES(`link_url`),
  `link_target` = VALUES(`link_target`),
  `target_paths` = VALUES(`target_paths`),
  `image_url` = VALUES(`image_url`),
  `image_asset_id` = VALUES(`image_asset_id`),
  `alt` = VALUES(`alt`),
  `text_behavior` = VALUES(`text_behavior`),
  `scroll_speed` = VALUES(`scroll_speed`),
  `closeable` = VALUES(`closeable`),
  `delay_seconds` = VALUES(`delay_seconds`),
  `display_frequency` = VALUES(`display_frequency`),
  `is_active` = VALUES(`is_active`),
  `display_order` = VALUES(`display_order`),
  `start_at` = VALUES(`start_at`),
  `end_at` = VALUES(`end_at`);

INSERT INTO `popups_i18n`
  (`popup_id`, `locale`, `title`, `content`, `button_text`, `alt`)
VALUES
  (1, 'tr', 'Toplu satış planlamasını erkenden başlatın', 'Yeni sezon için bayi, kooperatif ve kurumsal taleplerinizi toplu satış ekranından operasyon ekibine iletin.', 'Toplu Satışa Git', NULL),
  (1, 'en', 'Start bulk-sales planning early', 'Send dealer, cooperative, and corporate demand for the new season to the operations team through the bulk-sales flow.', 'Open Bulk Sales', NULL),
  (2, 'tr', 'Bilgi bankasında yeni teknik içerikler', 'Fide dikimi, sera geçişi ve ürün kararlarını destekleyen güncel rehberleri bilgi bankasında inceleyin.', 'Bilgi Bankasını Aç', 'Bilgi bankası popup görseli'),
  (2, 'en', 'New technical guides in the knowledge base', 'Review updated guides that support seedling transplant, greenhouse transition, and product decisions in the knowledge base.', 'Open Knowledge Base', 'Knowledge base popup visual'),
  (3, 'tr', 'Bayi ağı görünürlüğünü inceleyin', 'Bölgesel dağıtım yapımızı ve saha erişim modelimizi bayi ağı sayfasında görüntüleyin.', 'Bayi Ağını Aç', 'Bayi ağı popup görseli'),
  (3, 'en', 'Explore dealer network visibility', 'See our regional distribution structure and field access model on the dealer network page.', 'Open Dealer Network', 'Dealer network popup visual')
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `content` = VALUES(`content`),
  `button_text` = VALUES(`button_text`),
  `alt` = VALUES(`alt`);
