INSERT INTO `offers` (
  `id`, `offer_no`, `status`, `source`, `locale`, `country_code`,
  `customer_name`, `company_name`, `email`, `phone`,
  `subject`, `message`, `product_id`, `form_data`,
  `consent_marketing`, `consent_terms`,
  `currency`, `net_total`, `vat_rate`, `vat_total`, `shipping_total`, `gross_total`,
  `admin_notes`
) VALUES
(
  '99999999-9999-4999-8999-999999999991',
  'VS-2026-0001',
  'quoted',
  'toplu-satis',
  'tr',
  'Türkiye',
  'Mehmet Kaya',
  'Antalya Üretici Birliği',
  'mehmet.kaya@example.com',
  '+90 532 440 1122',
  'LUCKY F1 için sezon öncesi toplu alım talebi',
  'Mart sonu sevkiyat planına uygun olacak şekilde 12.000 adet LUCKY F1 için fiyat, teslim takvimi ve paketleme detaylarını paylaşmanızı rica ederiz.',
  'pppppppp-0001-4000-8000-000000000002',
  '{"hedef":"ilkbahar üretimi","adet":"12000","kanal":"bayi ağı"}',
  0,
  1,
  'EUR',
  1240.00,
  20.00,
  248.00,
  90.00,
  1578.00,
  'Telefon görüşmesi tamamlandı. Bölgesel dağıtım planına göre revize teklif hazırlanıyor.'
),
(
  '99999999-9999-4999-8999-999999999992',
  'VS-2026-0002',
  'new',
  'teklif-al',
  'en',
  'Germany',
  'Laura Becker',
  'GreenField GmbH',
  'laura.becker@example.com',
  '+49 151 2223344',
  'Quotation request for KIZGIN F1 greenhouse program',
  'Please share pricing, lead time, and packaging details for 8,000 units of KIZGIN F1 planned for greenhouse production.',
  'pppppppp-0001-4000-8000-000000000003',
  '{"season":"summer","channel":"website","units":"8000"}',
  1,
  1,
  'EUR',
  920.00,
  19.00,
  174.80,
  45.00,
  1139.80,
  NULL
)
ON DUPLICATE KEY UPDATE
  `offer_no` = VALUES(`offer_no`),
  `status` = VALUES(`status`),
  `source` = VALUES(`source`),
  `locale` = VALUES(`locale`),
  `country_code` = VALUES(`country_code`),
  `customer_name` = VALUES(`customer_name`),
  `company_name` = VALUES(`company_name`),
  `email` = VALUES(`email`),
  `phone` = VALUES(`phone`),
  `subject` = VALUES(`subject`),
  `message` = VALUES(`message`),
  `product_id` = VALUES(`product_id`),
  `form_data` = VALUES(`form_data`),
  `consent_marketing` = VALUES(`consent_marketing`),
  `consent_terms` = VALUES(`consent_terms`),
  `currency` = VALUES(`currency`),
  `net_total` = VALUES(`net_total`),
  `vat_rate` = VALUES(`vat_rate`),
  `vat_total` = VALUES(`vat_total`),
  `shipping_total` = VALUES(`shipping_total`),
  `gross_total` = VALUES(`gross_total`),
  `admin_notes` = VALUES(`admin_notes`);
