-- Vista Seeds homepage media and content refresh from official source
-- Source: https://www.vistaseeds.com.tr/
SET NAMES utf8mb4;
SET time_zone = '+00:00';

DELETE FROM `storage_assets` WHERE id LIKE '14709400-%';
INSERT INTO `storage_assets` (`id`,`name`,`bucket`,`path`,`folder`,`mime`,`size`,`url`,`provider`,`provider_public_id`,`provider_resource_type`,`provider_format`) VALUES ('14709400-0000-4000-8000-000000000001','tohumun-bereketi-01KKF1351HG1HJ9VJ2NCNC1EA7.webp','default','homepage/vistaseeds/features/tohumun-bereketi-01KKF1351HG1HJ9VJ2NCNC1EA7.webp','homepage/vistaseeds/features','image/webp',72864,'/uploads/homepage/vistaseeds/features/tohumun-bereketi-01KKF1351HG1HJ9VJ2NCNC1EA7.webp','local','homepage/vistaseeds/features/tohumun-bereketi-01KKF1351HG1HJ9VJ2NCNC1EA7.webp','image','webp') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `path`=VALUES(`path`), `folder`=VALUES(`folder`), `mime`=VALUES(`mime`), `size`=VALUES(`size`), `url`=VALUES(`url`), `provider`=VALUES(`provider`), `provider_public_id`=VALUES(`provider_public_id`), `provider_resource_type`=VALUES(`provider_resource_type`), `provider_format`=VALUES(`provider_format`);
INSERT INTO `storage_assets` (`id`,`name`,`bucket`,`path`,`folder`,`mime`,`size`,`url`,`provider`,`provider_public_id`,`provider_resource_type`,`provider_format`) VALUES ('14709400-0000-4000-8000-000000000002','yuksek-verimli-tohumlar-01KKBNPQNZ111C9XNQ5SZR917C.webp','default','homepage/vistaseeds/features/yuksek-verimli-tohumlar-01KKBNPQNZ111C9XNQ5SZR917C.webp','homepage/vistaseeds/features','image/webp',55652,'/uploads/homepage/vistaseeds/features/yuksek-verimli-tohumlar-01KKBNPQNZ111C9XNQ5SZR917C.webp','local','homepage/vistaseeds/features/yuksek-verimli-tohumlar-01KKBNPQNZ111C9XNQ5SZR917C.webp','image','webp') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `path`=VALUES(`path`), `folder`=VALUES(`folder`), `mime`=VALUES(`mime`), `size`=VALUES(`size`), `url`=VALUES(`url`), `provider`=VALUES(`provider`), `provider_public_id`=VALUES(`provider_public_id`), `provider_resource_type`=VALUES(`provider_resource_type`), `provider_format`=VALUES(`provider_format`);
INSERT INTO `storage_assets` (`id`,`name`,`bucket`,`path`,`folder`,`mime`,`size`,`url`,`provider`,`provider_public_id`,`provider_resource_type`,`provider_format`) VALUES ('14709400-0000-4000-8000-000000000003','surdurulebilir-tarim-01KKBP4H1ZRJG4NC56YH86XW1K.webp','default','homepage/vistaseeds/features/surdurulebilir-tarim-01KKBP4H1ZRJG4NC56YH86XW1K.webp','homepage/vistaseeds/features','image/webp',65048,'/uploads/homepage/vistaseeds/features/surdurulebilir-tarim-01KKBP4H1ZRJG4NC56YH86XW1K.webp','local','homepage/vistaseeds/features/surdurulebilir-tarim-01KKBP4H1ZRJG4NC56YH86XW1K.webp','image','webp') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `path`=VALUES(`path`), `folder`=VALUES(`folder`), `mime`=VALUES(`mime`), `size`=VALUES(`size`), `url`=VALUES(`url`), `provider`=VALUES(`provider`), `provider_public_id`=VALUES(`provider_public_id`), `provider_resource_type`=VALUES(`provider_resource_type`), `provider_format`=VALUES(`provider_format`);
INSERT INTO `storage_assets` (`id`,`name`,`bucket`,`path`,`folder`,`mime`,`size`,`url`,`provider`,`provider_public_id`,`provider_resource_type`,`provider_format`) VALUES ('14709400-0000-4000-8000-000000000004','kalite-ve-guven-01KKBP4HBBKX99XTFY3PV0YNVD.webp','default','homepage/vistaseeds/features/kalite-ve-guven-01KKBP4HBBKX99XTFY3PV0YNVD.webp','homepage/vistaseeds/features','image/webp',65946,'/uploads/homepage/vistaseeds/features/kalite-ve-guven-01KKBP4HBBKX99XTFY3PV0YNVD.webp','local','homepage/vistaseeds/features/kalite-ve-guven-01KKBP4HBBKX99XTFY3PV0YNVD.webp','image','webp') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `path`=VALUES(`path`), `folder`=VALUES(`folder`), `mime`=VALUES(`mime`), `size`=VALUES(`size`), `url`=VALUES(`url`), `provider`=VALUES(`provider`), `provider_public_id`=VALUES(`provider_public_id`), `provider_resource_type`=VALUES(`provider_resource_type`), `provider_format`=VALUES(`provider_format`);
INSERT INTO `storage_assets` (`id`,`name`,`bucket`,`path`,`folder`,`mime`,`size`,`url`,`provider`,`provider_public_id`,`provider_resource_type`,`provider_format`) VALUES ('14709400-0000-4000-8000-000000000005','neden-bizi-secmelisiniz-01KK93KQEVWW8KD5JD84V8ZZMZ.webp','default','homepage/vistaseeds/why-choose/neden-bizi-secmelisiniz-01KK93KQEVWW8KD5JD84V8ZZMZ.webp','homepage/vistaseeds/why-choose','image/webp',57764,'/uploads/homepage/vistaseeds/why-choose/neden-bizi-secmelisiniz-01KK93KQEVWW8KD5JD84V8ZZMZ.webp','local','homepage/vistaseeds/why-choose/neden-bizi-secmelisiniz-01KK93KQEVWW8KD5JD84V8ZZMZ.webp','image','webp') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `path`=VALUES(`path`), `folder`=VALUES(`folder`), `mime`=VALUES(`mime`), `size`=VALUES(`size`), `url`=VALUES(`url`), `provider`=VALUES(`provider`), `provider_public_id`=VALUES(`provider_public_id`), `provider_resource_type`=VALUES(`provider_resource_type`), `provider_format`=VALUES(`provider_format`);

INSERT INTO `site_settings` (`id`,`key`,`locale`,`value`) VALUES (UUID(), 'homepage_hero', 'tr', '{"season": "spring", "title": "Tohumun Bereketi", "highlight": "Vista Seeds", "suffix": "ile başlar", "description": "Tarımda başarı, doğru tohumla başlar. Vista Seeds olarak üreticilerin ihtiyaçlarını anlayan ve sahadaki gerçeklere uygun çözümler sunan bir anlayışla çalışıyoruz.", "badge": "Geleceğin Tarımı için Güçlü Tohumlar", "image_url": "/uploads/homepage/vistaseeds/features/tohumun-bereketi-01KKF1351HG1HJ9VJ2NCNC1EA7.webp", "cta_label": "Ürünleri Keşfet", "cta_href": "/urunler", "secondary_label": "Referansları İncele", "secondary_href": "/referanslar"}') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = NOW(3);

INSERT INTO `site_settings` (`id`,`key`,`locale`,`value`) VALUES (UUID(), 'trust_badges', 'tr', '[{"icon": "shield-check", "label": "Tescilli ve güvenilir çeşitler", "description": "Yüksek kaliteli tohum odağı"}, {"icon": "leaf", "label": "Sürdürülebilir gelecek vizyonu", "description": "Çevreci ve yenilenebilir yaklaşım"}, {"icon": "flask-conical", "label": "Tarımda sürekli gelişim", "description": "İnovasyon ve kalite çizgisi"}, {"icon": "sprout", "label": "Üretici odaklı yaklaşım", "description": "Saha gerçeklerine uygun çözümler"}]') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = NOW(3);

INSERT INTO `site_settings` (`id`,`key`,`locale`,`value`) VALUES (UUID(), 'homepage_sections', 'tr', '{"stats": [{"value": "1988", "label": "İlk Tarım Adımı"}, {"value": "2006", "label": "Bereket Fide"}, {"value": "100+", "label": "Uzman Kadro"}, {"value": "250+", "label": "Saha Ekibi"}], "values": [{"icon": "sun", "title": "Tescilli ve Güvenilir Çeşitler", "description": "Kaynak sitede vurgulanan yüksek kaliteli ve güvenilir çeşit anlayışı, ürün yüzeylerinde seçimi kolaylaştıran yapıyla sunulur."}, {"icon": "shield", "title": "Üretici Odaklı Yaklaşım", "description": "Üreticilerin ihtiyaçlarını anlayan ve sahadaki gerçeklere uygun çözüm geliştiren yaklaşım merkezdedir."}, {"icon": "users", "title": "Güçlü Kurumsal Altyapı", "description": "Tarım, enerji ve mühendislik yatırımlarıyla desteklenen çok yönlü kurumsal yapı görünür kılınır."}, {"icon": "beaker", "title": "Tarımda Sürekli Gelişim", "description": "İnovasyon, kalite ve sürdürülebilirlik odaklı büyüme çizgisi dijital içerik ve operasyon yüzeylerine taşınır."}, {"icon": "leaf", "title": "Sürdürülebilir Gelecek Vizyonu", "description": "Yenilenebilir enerji ve çevreci üretim yaklaşımı, kurumsal anlatının kalıcı unsuru olarak konumlanır."}], "timeline": [{"year": "1988", "title": "Tarım sektörüne ilk adım", "description": "Kurumsal gelişim çizgisinin başlangıç eşiği."}, {"year": "1990", "title": "Şahin Ziraat kuruluşu", "description": "Tarım odağındaki ilk yapılanma."}, {"year": "2006", "title": "Bereket Fide’nin kuruluşu", "description": "Üretim zincirini destekleyen fide operasyonu."}, {"year": "2017", "title": "İnşaat sektörüne giriş", "description": "Kurumsal yapının yeni yatırım alanlarına genişlemesi."}, {"year": "2018", "title": "Tolkan Mimarlık", "description": "Mühendislik ve proje tecrübesinin güçlenmesi."}, {"year": "2025", "title": "Atakan Tohum ve Vista Seeds kuruluşu", "description": "Mevcut kurumsal markanın görünür hale gelmesi."}], "seasonal_picks_title": "Öne Çıkan Çeşitler", "seasonal_picks_description": "Resmî ana sayfa anlatısındaki kalite ve verim ekseniyle seçilmiş ürün yüzeyi."}') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = NOW(3);

INSERT INTO `site_settings` (`id`,`key`,`locale`,`value`) VALUES (UUID(), 'homepage_feature_panels', 'tr', '{"title": "Görsel kurumsal yüzeyler", "subtitle": "Resmî ana sayfada öne çıkan anlatım blokları, yerel medya akışıyla VistaSeed ana sayfasına taşındı.", "items": [{"title": "Tohumun Bereketi", "description": "Tarımda başarının doğru tohumla başladığını vurgulayan ana mesaj.", "image_url": "/uploads/homepage/vistaseeds/features/tohumun-bereketi-01KKF1351HG1HJ9VJ2NCNC1EA7.webp", "image_alt": "Vista Seeds Tohumun Bereketi görseli"}, {"title": "Yüksek Verimli Tohumlar", "description": "Yüksek verim ve güvenilir çeşit odağını öne çıkaran görsel blok.", "image_url": "/uploads/homepage/vistaseeds/features/yuksek-verimli-tohumlar-01KKBNPQNZ111C9XNQ5SZR917C.webp", "image_alt": "Yüksek verimli tohumlar görseli"}, {"title": "Sürdürülebilir Tarım Anlayışı", "description": "Çevreye duyarlı üretim ve sürdürülebilir gelecek vurgusu.", "image_url": "/uploads/homepage/vistaseeds/features/surdurulebilir-tarim-01KKBP4H1ZRJG4NC56YH86XW1K.webp", "image_alt": "Sürdürülebilir tarım anlayışı görseli"}, {"title": "Kalite ve Güven", "description": "Kalite standartları ve güvenilir kurumsal yapı anlatısı.", "image_url": "/uploads/homepage/vistaseeds/features/kalite-ve-guven-01KKBP4HBBKX99XTFY3PV0YNVD.webp", "image_alt": "Kalite ve güven görseli"}], "cover_image_url": "/uploads/homepage/vistaseeds/why-choose/neden-bizi-secmelisiniz-01KK93KQEVWW8KD5JD84V8ZZMZ.webp", "cover_image_alt": "Neden bizi seçmelisiniz görseli"}') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = NOW(3);

UPDATE `custom_pages_i18n` SET
  `title` = 'Neden Vista Seeds?',
  `content` = '[{"icon": "sun", "title": "Tescilli ve Güvenilir Çeşitler", "description": "Kaynak sitede vurgulanan yüksek kaliteli ve güvenilir çeşit anlayışı, ürün yüzeylerinde seçimi kolaylaştıran yapıyla sunulur."}, {"icon": "shield", "title": "Üretici Odaklı Yaklaşım", "description": "Üreticilerin ihtiyaçlarını anlayan ve sahadaki gerçeklere uygun çözüm geliştiren yaklaşım merkezdedir."}, {"icon": "users", "title": "Güçlü Kurumsal Altyapı", "description": "Tarım, enerji ve mühendislik yatırımlarıyla desteklenen çok yönlü kurumsal yapı görünür kılınır."}, {"icon": "beaker", "title": "Tarımda Sürekli Gelişim", "description": "İnovasyon, kalite ve sürdürülebilirlik odaklı büyüme çizgisi dijital içerik ve operasyon yüzeylerine taşınır."}, {"icon": "leaf", "title": "Sürdürülebilir Gelecek Vizyonu", "description": "Yenilenebilir enerji ve çevreci üretim yaklaşımı, kurumsal anlatının kalıcı unsuru olarak konumlanır."}]',
  `summary` = 'Vista Seeds ile çalışmanın farkını ortaya koyan temel avantajlar ve öne çıkan değerler.'
WHERE `page_id` = 'neden-biz-uuid-001' AND `locale` = 'tr';
