-- =============================================================
-- 168 — dealer_profiles.logo_url
-- NO-OP. Kolon artik 133_dealer_finance_schema.sql icinde
-- CREATE TABLE tanimina dahil edilmistir (line 7).
-- ALTER TABLE lokal seed'de yasak (CLAUDE.md). Bu dosya, eski
-- migration kayitlari kirilmasin diye bos birakildi.
-- =============================================================
