-- Vista Seeds — 'Neden Vista Seeds?' (neden-biz) custom page EN/DE çevirileri
-- Ana sayfadaki values section başlık/kartları custom_pages_i18n'den gelir; tr'ye dokunmaz.
SET NAMES utf8mb4;

INSERT INTO `custom_pages_i18n` (`page_id`, `locale`, `title`, `slug`, `content`, `summary`) VALUES
  ('neden-biz-uuid-001', 'en', 'Why Vista Seeds?', 'neden-biz', '[{"icon": "sun", "title": "Registered and Reliable Varieties", "description": "A high-quality, registered and reliable variety portfolio, presented in a filterable and comparable form on the product pages."}, {"icon": "shield", "title": "Grower-Focused Approach", "description": "At the center is an approach that understands growers'' needs and develops solutions suited to field realities."}, {"icon": "users", "title": "Strong Corporate Infrastructure", "description": "A multifaceted corporate structure supported by investments in agriculture, energy and engineering."}, {"icon": "beaker", "title": "Continuous Improvement in Agriculture", "description": "Growth focused on innovation, quality and sustainability, supported by research and development processes."}, {"icon": "leaf", "title": "Sustainable Future Vision", "description": "A renewable-energy and eco-friendly production philosophy is the guiding principle in seed production and variety development."}]', 'Key advantages and standout values that reveal the difference of working with Vista Seeds.'),
  ('neden-biz-uuid-001', 'de', 'Warum Vista Seeds?', 'neden-biz', '[{"icon": "sun", "title": "Eingetragene und zuverlässige Sorten", "description": "Ein hochwertiges, eingetragenes und zuverlässiges Sortenportfolio, das auf den Produktseiten filter- und vergleichbar dargestellt wird."}, {"icon": "shield", "title": "Erzeugerorientierter Ansatz", "description": "Im Mittelpunkt steht ein Ansatz, der die Bedürfnisse der Erzeuger versteht und Lösungen entwickelt, die den Gegebenheiten auf dem Feld entsprechen."}, {"icon": "users", "title": "Starke Unternehmensinfrastruktur", "description": "Eine vielseitige Unternehmensstruktur, gestützt auf Investitionen in Landwirtschaft, Energie und Ingenieurwesen."}, {"icon": "beaker", "title": "Kontinuierliche Weiterentwicklung in der Landwirtschaft", "description": "Wachstum mit Fokus auf Innovation, Qualität und Nachhaltigkeit, unterstützt durch Forschungs- und Entwicklungsprozesse."}, {"icon": "leaf", "title": "Vision einer nachhaltigen Zukunft", "description": "Eine auf erneuerbare Energie und umweltfreundliche Produktion ausgerichtete Philosophie ist das Leitprinzip bei der Saatgutproduktion und Sortenentwicklung."}]', 'Wesentliche Vorteile und herausragende Werte, die den Unterschied einer Zusammenarbeit mit Vista Seeds zeigen.')
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `content` = VALUES(`content`),
  `summary` = VALUES(`summary`);
