export {
  EMAIL_TEMPLATES_ADMIN_BASE,
  type EmailTemplateAdminCreatePayload,
  type EmailTemplateAdminDetailDto,
  type EmailTemplateAdminListItemDto,
  type EmailTemplateAdminListQueryParams,
  type EmailTemplateAdminOrderBy,
  type EmailTemplateAdminTranslationDto,
  type EmailTemplateAdminUpdateArgs,
  type EmailTemplateAdminUpdatePayload,
  type EmailTemplateFormValues,
  type EmailTemplatePublicDto,
  type EmailTemplatePublicListQueryParams,
  type RenderEmailTemplateByKeyPayload,
  type RenderedEmailTemplateDto,
  normalizeEmailTemplateAdminDetail,
  normalizeEmailTemplateAdminList,
  toEmailTemplateWriteBody,
  toEmailTemplatesQuery,
} from '@/integrations/shared/email-templates';
