// =============================================================
// FILE: src/integrations/shared.ts
// Explicit barrel exports for active vistaseed modules
// =============================================================

export {
  ADMIN_IMAGE_LIBRARY_PAGE_SIZE,
  type AdminImageUploadFieldProps,
  appendUniqueUploadUrls,
  getDisplayUploadUrl,
  getUploadPreviewRatio,
  isSvgUploadUrl,
  normalizeUploadValue,
  sanitizeCloudinarySvgUrl,
  toUploadMetadata,
} from '@/integrations/shared/admin-image-upload';

export {
  DEFAULT_JSON_EDITOR_HEIGHT,
  DEFAULT_RICH_EDITOR_HEIGHT,
  type AdminJsonEditorProps,
  type RichContentEditorProps,
  type RichContentEditorTab,
  insertHtmlIntoCurrentSelection,
  normalizeLegacyRichHtml,
  parseEditorJson,
  stringifyEditorJson,
} from '@/integrations/shared/admin-editors';

export {
  type AdminLocaleMeta,
  type AdminLocaleOption,
  type AdminLocaleSelectProps,
  type AppLocaleItem,
  type UseAdminLocalesResult,
  buildAdminLocaleLabel,
  mapAdminLocaleFromUiValue,
  mapAdminLocaleToUiValue,
  normalizeAdminLocaleValue,
  parseAdminAppLocalesValue,
  toAdminLocaleOptions,
  toShortAdminLocale,
  uniqAdminLocalesByCode,
} from '@/integrations/shared/admin-locales';

export {
  ADMIN_TRANSLATIONS_PREFIX,
  ADMIN_UI_COPY_KEY,
  type UseAdminUiCopyResult,
  bindAdminTranslatePrefix,
} from '@/integrations/shared/admin-hooks';

export {
  CATEGORY_API_FALLBACK_ORIGIN,
  CATEGORY_DETAIL_INPUT_CLASS,
  CATEGORY_DEFAULT_LOCALE,
  CATEGORY_META_DESCRIPTION_LIMIT,
  CATEGORY_META_TITLE_LIMIT,
  CATEGORY_MODULE_KEYS,
  type CategoryLocaleOptionInput,
  type CategoryDetailFormState,
  type CategoryDetailTabKey,
  type CategoryModuleKey,
  buildCategoryImageSrc,
  buildCategoriesListQueryParams,
  buildCategoryLocaleOptions,
  buildCategorySeoPreviewUrl,
  buildCategoryToastMessage,
  createEmptyCategoryDetailForm,
  getCategoryApiOrigin,
  mapCategoryToDetailForm,
} from '@/integrations/shared/categories-config';

export {
  type ApiOk,
  type BoolLike,
  type DbBoolString,
  type HeaderDropdownItem,
  type HeaderMenuItem,
  type HeaderSocialItem,
  type ImgSrc,
  type JsonLike,
  type JsonObject,
  type MediaValue,
  type OffsetLimit,
  type QueryParamPrimitive,
  type QueryParamValue,
  type QueryParams,
  type SortOrder,
  type StaticImageLike,
  type UnknownRow,
  type ValueType,
  type WithLocale,
  asBoolLike,
  clamp,
  cx,
  extractArray,
  extractHtmlContent,
  extractTotal,
  getBoolProp,
  getErrorMessage,
  getNumberProp,
  getProp,
  getStringProp,
  isHttpUrl,
  isJsonishString,
  isObject,
  isPlainObject,
  isRemoteUrl,
  isUnknownRow,
  isUuidLike,
  isValidEmail,
  jsonLikeToBoolLike,
  nonEmpty,
  normSrc,
  numOrNullish,
  normalizeHeaderDropdownItems,
  normalizeHeaderMenu,
  normalizeHeaderSocialLinks,
  nullify,
  parseJsonArray,
  parseJsonObject,
  parseMediaUrl,
  parseSiteLogoMedia,
  pickDropdownKeys,
  pickFirst,
  pickHeaderCtaHrefFromUiHero,
  pickIsoOrNull,
  pickOptStr,
  pickStr,
  safeJsonLd,
  safeParseJson,
  safeText,
  shouldBypassNextImageOptimizer,
  stripHtmlToText,
  text,
  toAbsoluteUrlOrNull,
  toAbsoluteUrlStrict,
  toBool,
  toDbBoolString,
  toHtml,
  toInt,
  toIso,
  toNonNegativeInt,
  toNum,
  toNumOrNull,
  toNumSafe,
  toNumber,
  toStr,
  toStrArray,
  toStrArrayOrNull,
  toTrimStr,
  trimStr,
  trimOrUndef,
  truncateNullable,
  truncateText,
  tryParse,
  tryParseJsonVal,
  uiText,
  type NullableNumber,
  boolTo01,
  ensureArray,
} from '@/integrations/shared/common';

export { cleanParams, withQuery } from '@/integrations/shared/api';

export {
  ACCESS_TOKEN_STORAGE_KEY,
  AUTH_LOGIN_PATH,
  AUTH_SKIP_REAUTH,
  AUTH_SKIP_REAUTH_PATHS,
  REFRESH_TOKEN_STORAGE_KEY,
  createBrowserTokenStore,
  getDefaultLocale,
  readBrowserStorage,
  redirectToLogin,
  removeBrowserStorage,
  writeBrowserStorage,
} from '@/integrations/shared/auth-storage';

export {
  type FetchResult,
  type NormalizedError,
  type RTKError,
  coerceSerializableFetchErrorData,
  normalizeError,
} from '@/integrations/shared/errors';

export {
  type RequestArgs,
  ensureLeadingSlash,
  ensureRequestBodyHeaders,
  extractRequestPath,
  guessDevBackend,
  isAbsoluteUrl,
  isJsonLikeBody,
  isObjectRecord,
  isProbablyFormData,
  joinOriginAndBase,
  normalizeRequestArg,
  resolveBaseUrl,
  trimSlash,
} from '@/integrations/shared/network';

export {
  ADMIN_CONTACTS_DEFAULT_FILTERS,
  ADMIN_CONTACTS_ORDER_BY_OPTIONS,
  ADMIN_CONTACTS_ORDER_OPTIONS,
  ADMIN_CONTACTS_STATUS_OPTIONS,
  CONTACTS_ADMIN_BASE,
  type AdminContactsEditState,
  type AdminContactsFilters,
  type AdminContactsOrder,
  type AdminContactsOrderBy,
  type Contact,
  type ContactCreatePayload,
  type ContactDto,
  type ContactListQueryParams,
  type ContactStatus,
  type ContactUpdatePayload,
  type ContactView,
  buildAdminContactsListParams,
  createAdminContactEditState,
  formatAdminContactDateYmd,
  getAdminContactStatusKey,
  getAdminContactStatusVariant,
  normalizeContact,
} from '@/integrations/shared/contacts/index';

export {
  ADMIN_CARRIERS_ACTIVE_ILAN_OPTIONS,
  ADMIN_CARRIERS_ACTIVE_OPTIONS,
  ADMIN_CARRIERS_DEFAULT_FILTERS,
  ADMIN_CARRIERS_RECENT_LIMIT,
  CARRIERS_ADMIN_BASE,
  type AdminCarriersActiveFilter,
  type AdminCarriersFilters,
  type AdminCarriersHasIlanFilter,
  type CarrierDetail,
  type CarrierDetailBooking,
  type CarrierDetailBookingDto,
  type CarrierDetailDto,
  type CarrierDetailIlan,
  type CarrierDetailIlanDto,
  type CarrierDetailRating,
  type CarrierDetailRatingDto,
  type CarrierDetailStats,
  type CarrierDetailStatsDto,
  type CarrierListItem,
  type CarrierListItemDto,
  type CarrierListQueryParams,
  type CarrierListResponse,
  type CarrierListResponseDto,
  buildAdminCarrierDetailHref,
  buildAdminCarriersListParams,
  formatAdminCarrierDate,
  formatAdminCarrierMoney,
  formatAdminCarrierRating,
  getAdminCarrierDisplayName,
  getAdminCarrierStatusKey,
  getAdminCarrierWalletStatusKey,
  normalizeCarrierDetail,
  normalizeCarrierDetailBooking,
  normalizeCarrierDetailIlan,
  normalizeCarrierDetailRating,
  normalizeCarrierDetailStats,
  normalizeCarrierListItem,
  normalizeCarrierListResponse,
} from '@/integrations/shared/carriers/index';

export {
  type EmailRow,
  type EmailView,
  toView,
} from '@/integrations/shared/email/index';

export {
  type ListingBrandCreatePayload,
  type ListingBrandListParams,
  type ListingBrandPatchPayload,
  type ListingBrandView,
} from '@/integrations/shared/brand/index';

export {
  type CreateNotificationBody,
  type MarkAllReadBody,
  type NotificationRow,
  type NotificationType,
  type NotificationView,
  type NotificationsListParams,
  type OkResp,
  type UnreadCountResp,
  type UpdateNotificationBody,
  toCreateNotificationBody,
  toNotificationsListQuery,
  toUpdateNotificationBody,
} from '@/integrations/shared/notifications/index';

export {
  type ApiSliderAdmin,
  type ApiSliderPublic,
  type SliderAdminDto,
  type SliderAdminListQueryParams,
  type SliderAdminRow,
  type SliderAdminView,
  type SliderCreatePayload,
  type SliderPublicDetailQuery,
  type SliderPublicDto,
  type SliderPublicListQueryParams,
  type SliderReorderPayload,
  type SliderRow,
  type SliderSetImagePayload,
  type SliderSetStatusPayload,
  type SliderSortField,
  type SliderSortOrder,
  type SliderUpdatePayload,
  buildSliderParams,
  normalizeSliderAdmin,
  normalizeSliderPublic,
  toAdminSliderView,
} from '@/integrations/shared/slider/index';

export {
  type AdminSiteSetting,
  type AdminSiteSettingsListParams,
  type AppLocaleMeta,
  type BulkUpsertBody,
  type DeleteManySiteSettingsAdminArg,
  type DeleteSiteSettingAdminArg,
  type GetSiteSettingAdminByKeyArg,
  type PublicSiteSettingGetArg,
  type PublicSiteSettingsListArg,
  type SettingValue,
  type SiteSetting,
  type SiteSettingLike,
  type SiteSettingRow,
  type UiBlogCopy,
  type UiBrandsCopy,
  type UiCoporationCopy,
  type UiCoporationJournalItem,
  type UiHome3Copy,
  type UiHomeCopy,
  type UiProjectCopy,
  type UiResumeCopy,
  type UiResumeResearchItem,
  type UiServicesCopy,
  type UiSkillsCopy,
  type UiSkillsListItem,
  type UiStaticCopy,
  type UiStaticItem,
  type UpdateSiteSettingAdminArg,
  type UpsertSettingBody,
  SITE_SETTINGS_ADMIN_BASE,
  SITE_SETTINGS_ADMIN_LIST,
  buildAdminSiteSettingsListParams,
  buildDeleteManySiteSettingsParams,
  buildPublicSiteSettingsListParams,
  getSiteSettingsItemTags,
  getSiteSettingsUpdateTags,
  normalizeAdminSiteSettingRow,
  normalizeAdminSiteSettingsList,
  normalizeAppLocalesPublic,
  normalizeDefaultLocalePublic,
  normalizePublicSiteSetting,
  normalizePublicSiteSettingItem,
  normalizeSettingValue,
  normalizeSiteSettingKey,
  normalizeUiBlogSettingValue,
  normalizeUiBrandsSettingValue,
  normalizeUiCoporationSettingValue,
  normalizeUiHome3SettingValue,
  normalizeUiHomeSettingValue,
  normalizeUiProjectSettingValue,
  normalizeUiResumeSettingValue,
  normalizeUiServicesSettingValue,
  normalizeUiSkillsSettingValue,
  normalizeUiStaticSettingValue,
  resolveAdminSiteSettingKeyArg,
  resolveSiteSettingKeyArg,
  tryParsePublicValue,
} from '@/integrations/shared/site-settings';

export {
  coerceSiteSettingsPreviewValue,
  coerceSiteSettingsValue,
  getSiteSettingsActionErrorMessage,
  isSiteSettingsSeoKey,
  parseSiteSettingsRawValue,
  prettyStringifySiteSettingValue,
} from '@/integrations/shared/site-settings-ui';

export {
  SITE_SETTINGS_BRAND,
  SITE_SETTINGS_BRAND_PREFIX,
  SITE_SETTINGS_DEFAULTS_BY_KEY,
  SITE_SETTINGS_GENERAL_KEYS,
  SITE_SETTINGS_GLOBAL_TABS,
  SITE_SETTINGS_TABS,
  type SiteSettingsGeneralKey,
  type SiteSettingsGeneralRow,
  type SiteSettingsLocaleOption,
  type SiteSettingsLocaleRow,
  type SiteSettingsScope,
  type SiteSettingsTab,
  type SiteSettingsTabItem,
  buildSiteSettingsEditHref,
  buildSiteSettingsGeneralRows,
  buildSiteSettingsLocalePayload,
  buildSiteSettingsLocalesOptions,
  isSiteSettingsGeneralKey,
  isSiteSettingsGlobalTab,
  normalizeSiteSettingsLocaleRows,
  pickInitialSiteSettingsLocale,
  summariseSiteSettingsValue,
} from '@/integrations/shared/site-settings-config';

export {
  SITE_SETTINGS_INLINE_SEO_DEFAULT_EXPANDED_KEYS,
  SITE_SETTINGS_INLINE_SEO_PAGES,
  SITE_SETTINGS_INLINE_SEO_PREVIEW_HOST,
  SITE_SETTINGS_INLINE_SEO_PREVIEW_HOST_WWW,
  type SiteSettingsInlineSeoPage,
  type SiteSettingsInlineSeoPageKey,
  type SiteSettingsInlineSeoPages,
  buildSiteSettingsInlineSeoPreviewPath,
  coerceSiteSettingsInlineSeoValue,
  createEmptySiteSettingsInlineSeoPage,
  extractSiteSettingsInlineSeoPages,
} from '@/integrations/shared/site-settings-inline-seo-config';

export {
  EMPTY_SITE_SETTINGS_SMTP_FORM,
  SITE_SETTINGS_SMTP_KEYS,
  type SiteSettingsSmtpForm,
  type SiteSettingsSmtpKey,
  type SiteSettingsSmtpTestResult,
  buildSiteSettingsSmtpUpdates,
  createSiteSettingsSmtpForm,
  getSiteSettingsSmtpErrorMessage,
  mapSiteSettingsToSmtpForm,
} from '@/integrations/shared/site-settings-smtp-config';

export {
  EMPTY_SITE_SETTINGS_CLOUDINARY_FORM,
  SITE_SETTINGS_CLOUDINARY_KEYS,
  type SiteSettingsCloudinaryForm,
  type SiteSettingsCloudinaryKey,
  buildSiteSettingsCloudinaryUpdates,
  createSiteSettingsCloudinaryForm,
  getSiteSettingsCloudinaryErrorMessage,
  mapSiteSettingsToCloudinaryForm,
} from '@/integrations/shared/site-settings-cloudinary-config';

export {
  EMPTY_SITE_SETTINGS_API_FORM,
  SITE_SETTINGS_API_KEYS,
  SITE_SETTINGS_API_SECTIONS,
  type SiteSettingsApiFieldDef,
  type SiteSettingsApiForm,
  type SiteSettingsApiKey,
  type SiteSettingsApiSectionDef,
  type SiteSettingsApiTestResult,
  buildSiteSettingsApiUpdates,
  createSiteSettingsApiForm,
  getSiteSettingsApiErrorMessage,
  mapSiteSettingsToApiForm,
} from '@/integrations/shared/site-settings-api-config';

export {
  SITE_SETTINGS_BRAND_MEDIA_ITEMS,
  type SiteSettingsBrandMediaData,
  type SiteSettingsBrandMediaField,
  type SiteSettingsBrandMediaItem,
  buildSiteSettingsBrandMediaLegacyValue,
  createSiteSettingsBrandMediaData,
  extractSiteSettingsBrandMediaData,
  getSiteSettingsBrandMediaErrorMessage,
} from '@/integrations/shared/site-settings-brand-media-config';

export {
  EMPTY_SITE_SETTINGS_BRANDING_FORM,
  SITE_SETTINGS_BRANDING_PLACEHOLDER_KEYS,
  type SiteSettingsBrandingForm,
  brandingToSiteSettingsForm,
  getSiteSettingsBrandingErrorMessage,
  mergeSiteSettingsBrandingConfig,
  normalizeSiteSettingsBrandingConfig,
  siteSettingsFormToBranding,
} from '@/integrations/shared/site-settings-branding-config';

export {
  type SiteSettingsStructuredRendererKey,
  buildSiteSettingsDetailLocaleOptions,
  coerceSiteSettingsDetailValue,
  isSeoSiteSettingsKey,
  pickInitialSiteSettingsDetailLocale,
  resolveSiteSettingsStructuredRendererKey,
  toShortSiteSettingsLocale,
} from '@/integrations/shared/site-settings-detail-config';

export {
  type SiteSettingsAdvancedSeo,
  type SiteSettingsSimpleSeo,
  SITE_SETTINGS_AVAILABLE_LANGUAGES,
  SITE_SETTINGS_BACKGROUND_EMPTY_ITEM,
  SITE_SETTINGS_COMPANY_PROFILE_EMPTY,
  SITE_SETTINGS_COMPANY_PROFILE_FIELDS,
  SITE_SETTINGS_BUSINESS_HOURS_EMPTY,
  SITE_SETTINGS_BUSINESS_HOUR_DAYS,
  SITE_SETTINGS_CONTACT_EMPTY,
  SITE_SETTINGS_CONTACT_FIELDS,
  SITE_SETTINGS_HERO_EMPTY,
  SITE_SETTINGS_HERO_MEDIA_FIELDS,
  SITE_SETTINGS_HERO_TEXT_FIELDS,
  SITE_SETTINGS_SEO_OG_TYPE_OPTIONS,
  SITE_SETTINGS_SEO_PAGE_CONFIG,
  SITE_SETTINGS_SEO_TWITTER_CARD_OPTIONS,
  SITE_SETTINGS_SOCIAL_KEYS,
  SITE_SETTINGS_UI_HEADER_EMPTY,
  SITE_SETTINGS_UI_HEADER_FIELDS,
  type SiteSettingsBusinessHourDay,
  type SiteSettingsSocialKey,
  coerceSiteSettingsStructuredValue,
  isSiteSettingsSimpleSeoValue,
  normalizeSiteSettingsAdvancedSeo,
  normalizeSiteSettingsSimpleSeo,
  toSiteSettingsAdvancedSeoObject,
  toStructuredObjectSeed,
} from '@/integrations/shared/site-settings-structured-config';

export {
  ADMIN_STORAGE_ALL_OPTION,
  ADMIN_STORAGE_DEFAULT_BUCKET,
  ADMIN_STORAGE_DEFAULT_FILTERS,
  ADMIN_STORAGE_DEFAULT_LIMIT,
  ADMIN_STORAGE_MIME_OPTIONS,
  type ApiStorageAsset,
  type AdminStorageDetailFormData,
  type AdminStorageFilters,
  type BulkCreateErrorItem,
  type BulkCreateResponse,
  type ListResponse,
  type StorageAsset,
  type StorageListParams,
  type StorageListQuery,
  type StorageMeta,
  type StoragePublicUploadResponse,
  type StorageServerUploadArgs,
  type StorageSignMultipartBody,
  type StorageSignMultipartResponse,
  type StorageUpdateInput,
  type UploadManyResponse,
  StorageListTags,
  buildAdminStorageListQuery,
  compactFiles,
  createAdminStorageDetailFormData,
  formatAdminStorageBytes,
  formatAdminStorageDateTime,
  getAdminStorageMimeColorClass,
  getAdminStorageMimeIcon,
  makeCustomError,
  sanitize,
  toQueryParams,
} from '@/integrations/shared/storage/index';

export {
  ADMIN_USERS_ALL_ROLES,
  type AdminOkResponse,
  ADMIN_USERS_BASE,
  ADMIN_USERS_DEFAULT_LIMIT,
  type AdminUserDto,
  type AdminUserListQueryParams,
  type AdminUserRoleName,
  type AdminRemoveUserBody,
  type AdminSetActiveBody,
  type AdminUserSetActivePayload,
  type AdminSetPasswordBody,
  type AdminUserSetPasswordPayload,
  type AdminSetRolesBody,
  type AdminUserSetRolesPayload,
  type AdminUpdateUserBody,
  type AdminUserUpdatePayload,
  type AdminUserRaw,
  type AdminUserView,
  type AdminUsersListParams,
  type AuthMeNormalized,
  type AuthMeResponse,
  type AuthSignupBody,
  type AuthStatusResponse,
  type AuthTokenBody,
  type AuthTokenRefreshResponse,
  type AuthTokenResponse,
  type AuthUpdateBody,
  type AuthUser,
  type GetMyProfileArg,
  type GetMyProfileResp,
  type PasswordResetConfirmBody,
  type PasswordResetConfirmResponse,
  type PasswordResetRequestBody,
  type PasswordResetRequestResponse,
  type Profile,
  type ProfileRow,
  type ProfileSocial,
  type ProfileUpsertInput,
  type UpsertMyProfileArg,
  type UpsertMyProfileReq,
  type UpsertMyProfileResp,
  type UserRole,
  type UserRoleName,
  type UserRolesListParams,
  buildAdminUsersListParams,
  getAdminUserDisplayName,
  getAdminUserPrimaryRole,
  getAdminUserRoleLocaleKey,
  getAdminUsersNextOffset,
  getAdminUsersPreviousOffset,
  isAdminUserView,
  normalizeAdminUser,
  normalizeMeFromStatus,
  normalizeProfile,
  parseAdminUsersBoolParam,
  pickAdminUsersQuery,
  toAdminUsersSearchParams,
  type MaybeUsersListResponse,
  unwrapAdminUser,
  unwrapAdminUsersList,
} from '@/integrations/shared/users';

export {
  EMAIL_TEMPLATES_ADMIN_BASE,
  type EmailTemplateAdminCreatePayload,
  type EmailTemplateAdminDetailDto,
  type EmailTemplateAdminListItemDto,
  type EmailTemplateAdminListQueryParams,
  type EmailTemplateAdminOrderBy,
  type EmailTemplateAdminTranslationDto,
  type EmailTemplateAdminUpdateArgs,
  type EmailTemplateAdminUpdatePayload,
  type EmailTemplateFormValues,
  type EmailTemplatePublicDto,
  type EmailTemplatePublicListQueryParams,
  type RenderEmailTemplateByKeyPayload,
  type RenderedEmailTemplateDto,
  normalizeEmailTemplateAdminDetail,
  normalizeEmailTemplateAdminList,
  toEmailTemplateWriteBody,
  toEmailTemplatesQuery,
} from '@/integrations/shared/email-templates';

export {
  type AppLocale,
  parseAppLocales,
} from '@/integrations/shared/locales/index';

export {
  ADMIN_DASHBOARD_MODULES,
  ADMIN_DASHBOARD_ROUTE_MAP,
  ADMIN_DASHBOARD_SUMMARY_PERMISSION_MAP,
  type DashboardModule,
  type DashboardModuleKey,
  type AdminDashboardAnalyticsQuery,
  type DashboardAnalyticsDto,
  type DashboardCountItemDto,
  type DashboardRangeKey,
  type DashboardRecentOrderDto,
  type DashboardSummary,
  type DashboardSummaryItem,
  type DashboardTrendBucket,
  normalizeDashboardSummary,
} from '@/integrations/shared/dashboard/index';

export {
  type BlogPageCopy,
  type PricingPageCopy,
  type ServicesPageCopy,
  type WorkPageCopy,
  normalizeBlogPageCopy,
  normalizePricingPageCopy,
  normalizeServicesPageCopy,
  normalizeWorkPageCopy,
} from '@/integrations/shared/page-copies/index';

export {
  type AdminUiCommonCopy,
  type AdminUiCopy,
  type AdminUiPageCopy,
  normalizeAdminUiCopy,
} from '@/integrations/shared/admin-ui/index';

export {
  type KpiRow,
  type LocationRow,
  type ReportRole,
  type UserPerformanceRow,
} from '@/integrations/shared/reports/index';

export {
  ADMIN_AUDIT_ALL_VALUE,
  type AdminAuditBadgeVariant,
  type AdminAuditSortKey,
  type AdminAuditTabKey,
  AUDIT_ADMIN_BASE,
  AUDIT_AUTH_EVENTS,
  buildAdminAuditQueryString,
  formatAdminAuditWhen,
  getAdminAuditAuthEventVariant,
  getAdminAuditGeoLabel,
  getAdminAuditStatusVariant,
  normalizeAdminAuditBoolLike,
  normalizeAdminAuditTab,
  parseAdminAuditStatusCode,
  type AuditAuthEvent,
  type AuditAuthEventDto,
  type AuditAuthEventsListQueryParams,
  type AuditGeoStatsQueryParams,
  type AuditGeoStatsResponseDto,
  type AuditGeoStatsRowDto,
  type AuditListResponse,
  type AuditMetricsDailyDto,
  type AuditMetricsDailyQueryParams,
  type AuditMetricsDailyResponseDto,
  type AuditMetricsDailyRowDto,
  type AuditRequestLogDto,
  type AuditRequestLogsListQueryParams,
  type ClearAuditResponse,
  type ClearAuditTarget,
  coerceAuditGeoStats,
  coerceAuditList,
  coerceAuditMetricsDaily,
} from '@/integrations/shared/audit';

export {
  formatTelegramInboundLocalDate,
  getTelegramInboundSenderName,
  TELEGRAM_BOOLEAN_SETTINGS_KEYS,
  type SimpleSuccessResp,
  TELEGRAM_EVENT_TOGGLES,
  TELEGRAM_ADMIN_BASE,
  TELEGRAM_AUTOREPLY_ADMIN_BASE,
  TELEGRAM_AUTOREPLY_DEFAULT_TEMPLATE,
  TELEGRAM_INBOUND_ADMIN_BASE,
  TELEGRAM_SETTINGS_KEYS,
  TELEGRAM_TEMPLATE_DEFS,
  applyTelegramTemplate,
  buildTelegramPreviewVars,
  createTelegramSettingsDefaults,
  type TelegramAdminEventBody,
  type TelegramAdminSendBody,
  type TelegramAdminTestBody,
  type TelegramAdminTestResp,
  type TelegramAutoReplyConfig,
  type TelegramAutoReplyMode,
  type TelegramAutoReplyUpdateBody,
  type TelegramEventToggleDef,
  type TelegramEventType,
  type TelegramInboundListParams,
  type TelegramInboundListResult,
  type TelegramInboundMessage,
  type TelegramNotificationBody,
  type TelegramSettingsKey,
  type TelegramSettingsModel,
  type TelegramTemplateDef,
  type TelegramTemplateVars,
  type TelegramUpdate,
  type TelegramWebhookResponse,
  buildTelegramNotificationEventBody,
  normalizeTelegramAutoReplyConfig,
  normalizeTelegramTemplateValue,
} from '@/integrations/shared/telegram/index';

export {
  type CategoryCreatePayload,
  type CategoryDto,
  type CategoryListQueryParams,
  type CategoryPublicListQueryParams,
  type CategoryReorderItem,
  type CategoryReorderPayload,
  type CategorySetImagePayload,
  type CategoryUpdatePayload,
} from '@/integrations/shared/categories/index';

export {
  THEME_ADMIN_BASE,
  COLOR_TOKEN_LABELS,
  DEFAULT_THEME_CONFIG,
  RADIUS_OPTIONS,
  THEME_COLOR_HEX_PLACEHOLDER,
  THEME_DARK_MODE_OPTIONS,
  THEME_FONT_BODY_PLACEHOLDER,
  THEME_FONT_HEADING_PLACEHOLDER,
  THEME_RADIUS_PREVIEW_SIZES,
  type ColorTokens,
  type LayoutBlock,
  type ThemeColors,
  type ThemeConfig,
  type ThemeConfigView,
  type ThemeDarkMode,
  type ThemeDarkModeOption,
  type ThemeNewsSection,
  type ThemePage,
  type ThemeRadius,
  type ThemeSection,
  type ThemeTypography,
  type ThemeUpdateInput,
  groupThemeColorTokens,
  normalizeThemeConfig,
  sanitizeHex,
  toThemeDraft,
} from '@/integrations/shared/theme';

export {
  ADMIN_BOOKINGS_EMPTY_VALUE,
  ADMIN_BOOKINGS_ROUTE_SEPARATOR,
  ADMIN_BOOKINGS_UNKNOWN_CITY,
  type BookingAdminItem,
  type BookingAdminListParams,
  type BookingAdminListResponse,
  type BookingStatus,
  type UpdateBookingStatusAdminPayload,
  formatAdminBookingDate,
  formatAdminBookingPrice,
  formatAdminBookingWeight,
  getAdminBookingRouteLabel,
  getAdminBookingStatusVariant,
} from '@/integrations/shared/bookings/index';

export {
  ADMIN_WALLET_LIST_PAGE_SIZE,
  ADMIN_WALLET_STATUS_BADGE_CLASS,
  ADMIN_WALLET_TRANSACTIONS_PAGE_SIZE,
  ADMIN_WALLET_TX_AMOUNT_CLASS,
  ADMIN_WALLET_TX_STATUS_BADGE_CLASS,
  ADMIN_WALLET_TX_TYPE_BADGE_CLASS,
  WALLET_ADMIN_BASE,
  WALLET_TRANSACTION_ADMIN_BASE,
  formatAdminWalletAmount,
  formatAdminWalletDateTime,
  getAdminWalletSignedAmountPrefix,
  type WalletAdminView,
  type WalletAdjustPayload,
  type WalletListResponse,
  type WalletStatus,
  type WalletStatusPayload,
  type WalletTransactionListResponse,
  type WalletTransactionsProps,
  type WalletTransactionView,
  type WalletTxStatus,
  type WalletTxStatusPayload,
  type WalletTxType,
} from '@/integrations/shared/wallet';

export {
  ADMIN_ILANLAR_EMPTY_VALUE,
  ADMIN_ILANLAR_ROUTE_SEPARATOR,
  ILANLAR_ADMIN_BASE,
  formatAdminIlanDate,
  formatAdminIlanPrice,
  formatAdminIlanWeight,
  getAdminIlanRouteLabel,
  getAdminIlanStatusVariant,
  type IlanAdminItem,
  type IlanAdminListParams,
  type IlanAdminListResponse,
  type IlanStatus,
  type UpdateIlanStatusAdminPayload,
  type VehicleType,
  buildIlanlarAdminListUrl,
} from '@/integrations/shared/ilanlar/index';
