// =============================================================
// FILE: src/integrations/shared.ts
// Explicit barrel exports for active vistaseed modules
// =============================================================

export {
  ADMIN_IMAGE_LIBRARY_PAGE_SIZE,
  type AdminImageUploadFieldProps,
  appendUniqueUploadUrls,
  getDisplayUploadUrl,
  getUploadPreviewRatio,
  isSvgUploadUrl,
  normalizeUploadValue,
  sanitizeCloudinarySvgUrl,
  toUploadMetadata,
} from "@/integrations/shared/admin-image-upload";

export {
  DEFAULT_JSON_EDITOR_HEIGHT,
  DEFAULT_RICH_EDITOR_HEIGHT,
  type AdminJsonEditorProps,
  type RichContentEditorProps,
  type RichContentEditorTab,
  insertHtmlIntoCurrentSelection,
  normalizeLegacyRichHtml,
  parseEditorJson,
  stringifyEditorJson,
} from "@/integrations/shared/admin-editors";

export {
  type AdminLocaleMeta,
  type AdminLocaleOption,
  type AdminLocaleSelectProps,
  type AppLocaleItem,
  type UseAdminLocalesResult,
  buildAdminLocaleLabel,
  mapAdminLocaleFromUiValue,
  mapAdminLocaleToUiValue,
  normalizeAdminLocaleValue,
  parseAdminAppLocalesValue,
  toAdminLocaleOptions,
  toShortAdminLocale,
  uniqAdminLocalesByCode,
} from "@/integrations/shared/admin-locales";

export {
  ADMIN_TRANSLATIONS_PREFIX,
  ADMIN_UI_COPY_KEY,
  type UseAdminUiCopyResult,
  bindAdminTranslatePrefix,
} from "@/integrations/shared/admin-hooks";

export {
  CATEGORY_API_FALLBACK_ORIGIN,
  CATEGORY_DETAIL_INPUT_CLASS,
  CATEGORY_DEFAULT_LOCALE,
  CATEGORY_META_DESCRIPTION_LIMIT,
  CATEGORY_META_TITLE_LIMIT,
  CATEGORY_MODULE_KEYS,
  type CategoryLocaleOptionInput,
  type CategoryDetailFormState,
  type CategoryDetailTabKey,
  type CategoryModuleKey,
  buildCategoryImageSrc,
  buildCategoriesListQueryParams,
  buildCategoryLocaleOptions,
  buildCategorySeoPreviewUrl,
  buildCategoryToastMessage,
  createEmptyCategoryDetailForm,
  getCategoryApiOrigin,
  mapCategoryToDetailForm,
} from "@/integrations/shared/categories-config";

export {
  type ApiOk,
  type BoolLike,
  type DbBoolString,
  type HeaderDropdownItem,
  type HeaderMenuItem,
  type HeaderSocialItem,
  type ImgSrc,
  type JsonLike,
  type JsonObject,
  type MediaValue,
  type OffsetLimit,
  type QueryParamPrimitive,
  type QueryParamValue,
  type QueryParams,
  type SortOrder,
  type StaticImageLike,
  type UnknownRow,
  type ValueType,
  type WithLocale,
  asBoolLike,
  clamp,
  cx,
  extractArray,
  extractHtmlContent,
  extractTotal,
  getBoolProp,
  getErrorMessage,
  getNumberProp,
  getProp,
  getStringProp,
  isHttpUrl,
  isJsonishString,
  isObject,
  isPlainObject,
  isRemoteUrl,
  isUnknownRow,
  isUuidLike,
  isValidEmail,
  jsonLikeToBoolLike,
  nonEmpty,
  normSrc,
  numOrNullish,
  normalizeHeaderDropdownItems,
  normalizeHeaderMenu,
  normalizeHeaderSocialLinks,
  nullify,
  parseJsonArray,
  parseJsonObject,
  parseMediaUrl,
  parseSiteLogoMedia,
  pickDropdownKeys,
  pickFirst,
  pickHeaderCtaHrefFromUiHero,
  pickIsoOrNull,
  pickOptStr,
  pickStr,
  safeJsonLd,
  safeParseJson,
  safeText,
  shouldBypassNextImageOptimizer,
  stripHtmlToText,
  text,
  toAbsoluteUrlOrNull,
  toAbsoluteUrlStrict,
  toBool,
  toDbBoolString,
  toHtml,
  toInt,
  toIso,
  toNonNegativeInt,
  toNum,
  toNumOrNull,
  toNumSafe,
  toNumber,
  toStr,
  toStrArray,
  toStrArrayOrNull,
  toTrimStr,
  trimStr,
  trimOrUndef,
  truncateNullable,
  truncateText,
  tryParse,
  tryParseJsonVal,
  uiText,
  type NullableNumber,
  boolTo01,
  ensureArray,
} from "@/integrations/shared/common";

export { cleanParams, withQuery } from "@/integrations/shared/api";

export {
  ACCESS_TOKEN_STORAGE_KEY,
  AUTH_LOGIN_PATH,
  AUTH_SKIP_REAUTH,
  AUTH_SKIP_REAUTH_PATHS,
  REFRESH_TOKEN_STORAGE_KEY,
  createBrowserTokenStore,
  getDefaultLocale,
  readBrowserStorage,
  redirectToLogin,
  removeBrowserStorage,
  writeBrowserStorage,
} from "@/integrations/shared/auth-storage";

export {
  type FetchResult,
  type NormalizedError,
  type RTKError,
  coerceSerializableFetchErrorData,
  normalizeError,
} from "@/integrations/shared/errors";

export {
  type RequestArgs,
  ensureLeadingSlash,
  ensureRequestBodyHeaders,
  extractRequestPath,
  guessDevBackend,
  isAbsoluteUrl,
  isJsonLikeBody,
  isObjectRecord,
  isProbablyFormData,
  joinOriginAndBase,
  normalizeRequestArg,
  resolveBaseUrl,
  trimSlash,
} from "@/integrations/shared/network";

export {
  ADMIN_CONTACTS_DEFAULT_FILTERS,
  ADMIN_CONTACTS_ORDER_BY_OPTIONS,
  ADMIN_CONTACTS_ORDER_OPTIONS,
  ADMIN_CONTACTS_STATUS_OPTIONS,
  CONTACTS_ADMIN_BASE,
  type AdminContactsEditState,
  type AdminContactsFilters,
  type AdminContactsOrder,
  type AdminContactsOrderBy,
  type Contact,
  type ContactCreatePayload,
  type ContactDto,
  type ContactListQueryParams,
  type ContactStatus,
  type ContactUpdatePayload,
  type ContactView,
  buildAdminContactsListParams,
  createAdminContactEditState,
  formatAdminContactDateYmd,
  getAdminContactStatusKey,
  getAdminContactStatusVariant,
  normalizeContact,
} from "@/integrations/shared/contacts/index";

export {
  type EmailRow,
  type EmailView,
  toView,
} from "@/integrations/shared/email/index";

export {
  type ListingBrandCreatePayload,
  type ListingBrandListParams,
  type ListingBrandPatchPayload,
  type ListingBrandView,
} from "@/integrations/shared/brand/index";

export {
  type JobListingDto,
  type JobListingListQueryParams,
  type JobListingCreatePayload,
  type JobListingUpdatePayload,
  type JobListingReorderPayload,
  JOB_LISTINGS_ADMIN_BASE,
  JOB_LISTINGS_DEFAULT_LOCALE,
  type JobListingDetailTabKey,
  type JobEmploymentType,
  type JobListingDetailFormState,
  buildJobListingPayload,
  buildJobListingsListQueryParams,
  createEmptyJobListingDetailForm,
  mapJobListingToDetailForm,
} from "@/integrations/shared/job-listings";

export {
  BLOG_POST_DEFAULT_LOCALE,
  type BlogCategory,
  type BlogPostCreatePayload,
  type BlogPostDto,
  type BlogPostListQueryParams,
  type BlogPostUpdatePayload,
  type BlogRssImportPayload,
  type BlogRssImportResult,
  type BlogPostDetailTabKey,
  type BlogPostFormState,
  buildBlogPostPayload,
  buildBlogPostsListQueryParams,
  createEmptyBlogPostForm,
  mapBlogPostToForm,
} from "@/integrations/shared/blog";

export {
  OFFERS_ADMIN_BASE,
  OFFER_STATUSES,
  type OfferStatus,
  type OfferDto,
  type OfferListQueryParams,
  type OfferCreatePayload,
  type OfferUpdatePayload,
  type OfferDetailTabKey,
  type OfferDetailFormState,
  buildOffersListQueryParams,
  createEmptyOfferDetailForm,
  mapOfferToDetailForm,
  buildOfferPayload,
} from "@/integrations/shared/offers";

export {
  buildJobApplicationStatusPayload,
  buildJobApplicationsListQueryParams,
  JOB_APPLICATIONS_ADMIN_BASE,
  JOB_APPLICATIONS_DEFAULT_LOCALE,
  JOB_APPLICATION_STATUS_OPTIONS,
  mapJobApplicationToDetailForm,
  type JobApplicationDetailFormState,
} from "@/integrations/shared/job-applications";

export type {
  JobApplicationDto,
  JobApplicationListQueryParams,
  JobApplicationStatus,
  JobApplicationStatusPayload,
} from "@/integrations/shared/job-applications";

export {
  type CreateNotificationBody,
  type MarkAllReadBody,
  type NotificationRow,
  type NotificationType,
  type NotificationView,
  type NotificationsListParams,
  type OkResp,
  type UnreadCountResp,
  type UpdateNotificationBody,
  toCreateNotificationBody,
  toNotificationsListQuery,
  toUpdateNotificationBody,
} from "@/integrations/shared/notifications/index";

export {
  type ApiSliderAdmin,
  type ApiSliderPublic,
  type SliderAdminDto,
  type SliderAdminListQueryParams,
  type SliderAdminRow,
  type SliderAdminView,
  type SliderCreatePayload,
  type SliderPublicDetailQuery,
  type SliderPublicDto,
  type SliderPublicListQueryParams,
  type SliderReorderPayload,
  type SliderRow,
  type SliderSetImagePayload,
  type SliderSetStatusPayload,
  type SliderSortField,
  type SliderSortOrder,
  type SliderUpdatePayload,
  buildSliderParams,
  normalizeSliderAdmin,
  normalizeSliderPublic,
  toAdminSliderView,
} from "@/integrations/shared/slider/index";

export {
  type AdminSiteSetting,
  type AdminSiteSettingsListParams,
  type AppLocaleMeta,
  type BulkUpsertBody,
  type DeleteManySiteSettingsAdminArg,
  type DeleteSiteSettingAdminArg,
  type GetSiteSettingAdminByKeyArg,
  type PublicSiteSettingGetArg,
  type PublicSiteSettingsListArg,
  type SettingValue,
  type SiteSetting,
  type SiteSettingLike,
  type SiteSettingRow,
  type UiBlogCopy,
  type UiBrandsCopy,
  type UiCoporationCopy,
  type UiCoporationJournalItem,
  type UiHome3Copy,
  type UiHomeCopy,
  type UiProjectCopy,
  type UiResumeCopy,
  type UiResumeResearchItem,
  type UiServicesCopy,
  type UiSkillsCopy,
  type UiSkillsListItem,
  type UiStaticCopy,
  type UiStaticItem,
  type UpdateSiteSettingAdminArg,
  type UpsertSettingBody,
  SITE_SETTINGS_ADMIN_BASE,
  SITE_SETTINGS_ADMIN_LIST,
  buildAdminSiteSettingsListParams,
  buildDeleteManySiteSettingsParams,
  buildPublicSiteSettingsListParams,
  getSiteSettingsItemTags,
  getSiteSettingsUpdateTags,
  normalizeAdminSiteSettingRow,
  normalizeAdminSiteSettingsList,
  normalizeAppLocalesPublic,
  normalizeDefaultLocalePublic,
  normalizePublicSiteSetting,
  normalizePublicSiteSettingItem,
  normalizeSettingValue,
  normalizeSiteSettingKey,
  normalizeUiBlogSettingValue,
  normalizeUiBrandsSettingValue,
  normalizeUiCoporationSettingValue,
  normalizeUiHome3SettingValue,
  normalizeUiHomeSettingValue,
  normalizeUiProjectSettingValue,
  normalizeUiResumeSettingValue,
  normalizeUiServicesSettingValue,
  normalizeUiSkillsSettingValue,
  normalizeUiStaticSettingValue,
  resolveAdminSiteSettingKeyArg,
  resolveSiteSettingKeyArg,
  tryParsePublicValue,
} from "@/integrations/shared/site-settings";

export {
  coerceSiteSettingsPreviewValue,
  coerceSiteSettingsValue,
  getSiteSettingsActionErrorMessage,
  isSiteSettingsSeoKey,
  parseSiteSettingsRawValue,
  prettyStringifySiteSettingValue,
} from "@/integrations/shared/site-settings-ui";

export {
  SITE_SETTINGS_BRAND,
  SITE_SETTINGS_BRAND_PREFIX,
  SITE_SETTINGS_DEFAULTS_BY_KEY,
  SITE_SETTINGS_GENERAL_KEYS,
  SITE_SETTINGS_GLOBAL_TABS,
  SITE_SETTINGS_TABS,
  type SiteSettingsGeneralKey,
  type SiteSettingsGeneralRow,
  type SiteSettingsLocaleOption,
  type SiteSettingsLocaleRow,
  type SiteSettingsScope,
  type SiteSettingsTab,
  type SiteSettingsTabItem,
  buildSiteSettingsEditHref,
  buildSiteSettingsGeneralRows,
  buildSiteSettingsLocalePayload,
  buildSiteSettingsLocalesOptions,
  isSiteSettingsGeneralKey,
  isSiteSettingsGlobalTab,
  normalizeSiteSettingsLocaleRows,
  pickInitialSiteSettingsLocale,
  summariseSiteSettingsValue,
} from "@/integrations/shared/site-settings-config";

export {
  SITE_SETTINGS_INLINE_SEO_DEFAULT_EXPANDED_KEYS,
  SITE_SETTINGS_INLINE_SEO_PAGES,
  SITE_SETTINGS_INLINE_SEO_PREVIEW_HOST,
  SITE_SETTINGS_INLINE_SEO_PREVIEW_HOST_WWW,
  type SiteSettingsInlineSeoPage,
  type SiteSettingsInlineSeoPageKey,
  type SiteSettingsInlineSeoPages,
  buildSiteSettingsInlineSeoPreviewPath,
  coerceSiteSettingsInlineSeoValue,
  createEmptySiteSettingsInlineSeoPage,
  extractSiteSettingsInlineSeoPages,
} from "@/integrations/shared/site-settings-inline-seo-config";

export {
  EMPTY_SITE_SETTINGS_SMTP_FORM,
  SITE_SETTINGS_SMTP_KEYS,
  type SiteSettingsSmtpForm,
  type SiteSettingsSmtpKey,
  type SiteSettingsSmtpTestResult,
  buildSiteSettingsSmtpUpdates,
  createSiteSettingsSmtpForm,
  getSiteSettingsSmtpErrorMessage,
  mapSiteSettingsToSmtpForm,
} from "@/integrations/shared/site-settings-smtp-config";

export {
  EMPTY_SITE_SETTINGS_CLOUDINARY_FORM,
  SITE_SETTINGS_CLOUDINARY_KEYS,
  type SiteSettingsCloudinaryForm,
  type SiteSettingsCloudinaryKey,
  buildSiteSettingsCloudinaryUpdates,
  createSiteSettingsCloudinaryForm,
  getSiteSettingsCloudinaryErrorMessage,
  mapSiteSettingsToCloudinaryForm,
} from "@/integrations/shared/site-settings-cloudinary-config";

export {
  EMPTY_SITE_SETTINGS_API_FORM,
  SITE_SETTINGS_API_KEYS,
  SITE_SETTINGS_API_SECTIONS,
  type SiteSettingsApiFieldDef,
  type SiteSettingsApiForm,
  type SiteSettingsApiKey,
  type SiteSettingsApiSectionDef,
  type SiteSettingsApiTestResult,
  buildSiteSettingsApiUpdates,
  createSiteSettingsApiForm,
  getSiteSettingsApiErrorMessage,
  mapSiteSettingsToApiForm,
} from "@/integrations/shared/site-settings-api-config";

export {
  SITE_SETTINGS_BRAND_MEDIA_ITEMS,
  type SiteSettingsBrandMediaData,
  type SiteSettingsBrandMediaField,
  type SiteSettingsBrandMediaItem,
  buildSiteSettingsBrandMediaLegacyValue,
  createSiteSettingsBrandMediaData,
  extractSiteSettingsBrandMediaData,
  getSiteSettingsBrandMediaErrorMessage,
} from "@/integrations/shared/site-settings-brand-media-config";

export {
  EMPTY_SITE_SETTINGS_BRANDING_FORM,
  SITE_SETTINGS_BRANDING_PLACEHOLDER_KEYS,
  type SiteSettingsBrandingForm,
  brandingToSiteSettingsForm,
  getSiteSettingsBrandingErrorMessage,
  mergeSiteSettingsBrandingConfig,
  normalizeSiteSettingsBrandingConfig,
  siteSettingsFormToBranding,
} from "@/integrations/shared/site-settings-branding-config";

export {
  type SiteSettingsStructuredRendererKey,
  buildSiteSettingsDetailLocaleOptions,
  coerceSiteSettingsDetailValue,
  isSeoSiteSettingsKey,
  pickInitialSiteSettingsDetailLocale,
  resolveSiteSettingsStructuredRendererKey,
  toShortSiteSettingsLocale,
} from "@/integrations/shared/site-settings-detail-config";

export {
  type SiteSettingsAdvancedSeo,
  type SiteSettingsSimpleSeo,
  SITE_SETTINGS_AVAILABLE_LANGUAGES,
  SITE_SETTINGS_BACKGROUND_EMPTY_ITEM,
  SITE_SETTINGS_COMPANY_PROFILE_EMPTY,
  SITE_SETTINGS_COMPANY_PROFILE_FIELDS,
  SITE_SETTINGS_BUSINESS_HOURS_EMPTY,
  SITE_SETTINGS_BUSINESS_HOUR_DAYS,
  SITE_SETTINGS_CONTACT_EMPTY,
  SITE_SETTINGS_CONTACT_FIELDS,
  SITE_SETTINGS_HERO_EMPTY,
  SITE_SETTINGS_HERO_MEDIA_FIELDS,
  SITE_SETTINGS_HERO_TEXT_FIELDS,
  SITE_SETTINGS_SEO_OG_TYPE_OPTIONS,
  SITE_SETTINGS_SEO_PAGE_CONFIG,
  SITE_SETTINGS_SEO_TWITTER_CARD_OPTIONS,
  SITE_SETTINGS_SOCIAL_KEYS,
  SITE_SETTINGS_UI_HEADER_EMPTY,
  SITE_SETTINGS_UI_HEADER_FIELDS,
  type SiteSettingsBusinessHourDay,
  type SiteSettingsSocialKey,
  coerceSiteSettingsStructuredValue,
  isSiteSettingsSimpleSeoValue,
  normalizeSiteSettingsAdvancedSeo,
  normalizeSiteSettingsSimpleSeo,
  toSiteSettingsAdvancedSeoObject,
  toStructuredObjectSeed,
} from "@/integrations/shared/site-settings-structured-config";

export {
  ADMIN_STORAGE_ALL_OPTION,
  ADMIN_STORAGE_DEFAULT_BUCKET,
  ADMIN_STORAGE_DEFAULT_FILTERS,
  ADMIN_STORAGE_DEFAULT_LIMIT,
  ADMIN_STORAGE_MIME_OPTIONS,
  type ApiStorageAsset,
  type AdminStorageDetailFormData,
  type AdminStorageFilters,
  type BulkCreateErrorItem,
  type BulkCreateResponse,
  type ListResponse,
  type StorageAsset,
  type StorageListParams,
  type StorageListQuery,
  type StorageMeta,
  type StoragePublicUploadResponse,
  type StorageServerUploadArgs,
  type StorageSignMultipartBody,
  type StorageSignMultipartResponse,
  type StorageUpdateInput,
  type UploadManyResponse,
  StorageListTags,
  buildAdminStorageListQuery,
  compactFiles,
  createAdminStorageDetailFormData,
  formatAdminStorageBytes,
  formatAdminStorageDateTime,
  getAdminStorageMimeColorClass,
  getAdminStorageMimeIcon,
  makeCustomError,
  sanitize,
  toQueryParams,
} from "@/integrations/shared/storage/index";

export {
  ADMIN_USERS_ALL_ROLES,
  type AdminOkResponse,
  ADMIN_USERS_BASE,
  ADMIN_USERS_DEFAULT_LIMIT,
  type AdminUserDto,
  type AdminUserListQueryParams,
  type AdminUserRoleName,
  type AdminRemoveUserBody,
  type AdminSetActiveBody,
  type AdminUserSetActivePayload,
  type AdminSetPasswordBody,
  type AdminUserSetPasswordPayload,
  type AdminSetRolesBody,
  type AdminUserSetRolesPayload,
  type AdminUpdateUserBody,
  type AdminUserUpdatePayload,
  type AdminUserRaw,
  type AdminUserView,
  type AdminUsersListParams,
  type AuthMeNormalized,
  type AuthMeResponse,
  type AuthSignupBody,
  type AuthStatusResponse,
  type AuthTokenBody,
  type AuthTokenRefreshResponse,
  type AuthTokenResponse,
  type AuthUpdateBody,
  type AuthUser,
  type GetMyProfileArg,
  type GetMyProfileResp,
  type PasswordResetConfirmBody,
  type PasswordResetConfirmResponse,
  type PasswordResetRequestBody,
  type PasswordResetRequestResponse,
  type Profile,
  type ProfileRow,
  type ProfileSocial,
  type ProfileUpsertInput,
  type UpsertMyProfileArg,
  type UpsertMyProfileReq,
  type UpsertMyProfileResp,
  type UserRole,
  type UserRoleName,
  type UserRolesListParams,
  buildAdminUsersListParams,
  getAdminUserDisplayName,
  getAdminUserPrimaryRole,
  getAdminUserRoleLocaleKey,
  getAdminUsersNextOffset,
  getAdminUsersPreviousOffset,
  isAdminUserView,
  normalizeAdminUser,
  normalizeMeFromStatus,
  normalizeProfile,
  parseAdminUsersBoolParam,
  pickAdminUsersQuery,
  toAdminUsersSearchParams,
  type MaybeUsersListResponse,
  unwrapAdminUser,
  unwrapAdminUsersList,
} from "@/integrations/shared/users";

export {
  EMAIL_TEMPLATES_ADMIN_BASE,
  type EmailTemplateAdminCreatePayload,
  type EmailTemplateAdminDetailDto,
  type EmailTemplateAdminListItemDto,
  type EmailTemplateAdminListQueryParams,
  type EmailTemplateAdminOrderBy,
  type EmailTemplateAdminTranslationDto,
  type EmailTemplateAdminUpdateArgs,
  type EmailTemplateAdminUpdatePayload,
  type EmailTemplateFormValues,
  type EmailTemplatePublicDto,
  type EmailTemplatePublicListQueryParams,
  type RenderEmailTemplateByKeyPayload,
  type RenderedEmailTemplateDto,
  normalizeEmailTemplateAdminDetail,
  normalizeEmailTemplateAdminList,
  toEmailTemplateWriteBody,
  toEmailTemplatesQuery,
} from "@/integrations/shared/email-templates";

export {
  type AppLocale,
  parseAppLocales,
} from "@/integrations/shared/locales/index";

export {
  ADMIN_DASHBOARD_MODULES,
  ADMIN_DASHBOARD_ROUTE_MAP,
  ADMIN_DASHBOARD_SUMMARY_PERMISSION_MAP,
  type DashboardModule,
  type DashboardModuleKey,
  type AdminDashboardAnalyticsQuery,
  type DashboardAnalyticsDto,
  type DashboardCountItemDto,
  type DashboardRangeKey,
  type DashboardRecentOrderDto,
  type DashboardSummary,
  type DashboardSummaryItem,
  type DashboardTrendBucket,
  normalizeDashboardSummary,
} from "@/integrations/shared/dashboard/index";

export {
  type BlogPageCopy,
  type PricingPageCopy,
  type ServicesPageCopy,
  type WorkPageCopy,
  normalizeBlogPageCopy,
  normalizePricingPageCopy,
  normalizeServicesPageCopy,
  normalizeWorkPageCopy,
} from "@/integrations/shared/page-copies/index";

export {
  type AdminUiCommonCopy,
  type AdminUiCopy,
  type AdminUiPageCopy,
  normalizeAdminUiCopy,
} from "@/integrations/shared/admin-ui/index";

export {
  ADMIN_AUDIT_ALL_VALUE,
  type AdminAuditBadgeVariant,
  type AdminAuditSortKey,
  type AdminAuditTabKey,
  AUDIT_ADMIN_BASE,
  AUDIT_AUTH_EVENTS,
  buildAdminAuditQueryString,
  formatAdminAuditWhen,
  getAdminAuditAuthEventVariant,
  getAdminAuditGeoLabel,
  getAdminAuditStatusVariant,
  normalizeAdminAuditBoolLike,
  normalizeAdminAuditTab,
  parseAdminAuditStatusCode,
  type AuditAuthEvent,
  type AuditAuthEventDto,
  type AuditAuthEventsListQueryParams,
  type AuditGeoStatsQueryParams,
  type AuditGeoStatsResponseDto,
  type AuditGeoStatsRowDto,
  type AuditListResponse,
  type AuditMetricsDailyDto,
  type AuditMetricsDailyQueryParams,
  type AuditMetricsDailyResponseDto,
  type AuditMetricsDailyRowDto,
  type AuditRequestLogDto,
  type AuditRequestLogsListQueryParams,
  type ClearAuditResponse,
  type ClearAuditTarget,
  coerceAuditGeoStats,
  coerceAuditList,
  coerceAuditMetricsDaily,
} from "@/integrations/shared/audit";

export {
  formatTelegramInboundLocalDate,
  getTelegramInboundSenderName,
  TELEGRAM_BOOLEAN_SETTINGS_KEYS,
  type SimpleSuccessResp,
  TELEGRAM_EVENT_TOGGLES,
  TELEGRAM_ADMIN_BASE,
  TELEGRAM_AUTOREPLY_ADMIN_BASE,
  TELEGRAM_AUTOREPLY_DEFAULT_TEMPLATE,
  TELEGRAM_INBOUND_ADMIN_BASE,
  TELEGRAM_SETTINGS_KEYS,
  TELEGRAM_TEMPLATE_DEFS,
  applyTelegramTemplate,
  buildTelegramPreviewVars,
  createTelegramSettingsDefaults,
  type TelegramAdminEventBody,
  type TelegramAdminSendBody,
  type TelegramAdminTestBody,
  type TelegramAdminTestResp,
  type TelegramAutoReplyConfig,
  type TelegramAutoReplyMode,
  type TelegramAutoReplyUpdateBody,
  type TelegramEventToggleDef,
  type TelegramEventType,
  type TelegramInboundListParams,
  type TelegramInboundListResult,
  type TelegramInboundMessage,
  type TelegramNotificationBody,
  type TelegramSettingsKey,
  type TelegramSettingsModel,
  type TelegramTemplateDef,
  type TelegramTemplateVars,
  type TelegramUpdate,
  type TelegramWebhookResponse,
  buildTelegramNotificationEventBody,
  normalizeTelegramAutoReplyConfig,
  normalizeTelegramTemplateValue,
} from "@/integrations/shared/telegram/index";

export {
  type CategoryCreatePayload,
  type CategoryDto,
  type CategoryListQueryParams,
  type CategoryPublicListQueryParams,
  type CategoryReorderItem,
  type CategoryReorderPayload,
  type CategorySetImagePayload,
  type CategoryUpdatePayload,
} from "@/integrations/shared/categories/index";

export {
  THEME_ADMIN_BASE,
  COLOR_TOKEN_LABELS,
  DEFAULT_THEME_CONFIG,
  RADIUS_OPTIONS,
  THEME_COLOR_HEX_PLACEHOLDER,
  THEME_DARK_MODE_OPTIONS,
  THEME_FONT_BODY_PLACEHOLDER,
  THEME_FONT_HEADING_PLACEHOLDER,
  THEME_RADIUS_PREVIEW_SIZES,
  type ColorTokens,
  type LayoutBlock,
  type ThemeColors,
  type ThemeConfig,
  type ThemeConfigView,
  type ThemeDarkMode,
  type ThemeDarkModeOption,
  type ThemeNewsSection,
  type ThemePage,
  type ThemeRadius,
  type ThemeSection,
  type ThemeTypography,
  type ThemeUpdateInput,
  groupThemeColorTokens,
  normalizeThemeConfig,
  sanitizeHex,
  toThemeDraft,
} from "@/integrations/shared/theme";

export {
  PRODUCTS_ADMIN_BASE,
  PRODUCT_DEFAULT_LOCALE,
  PRODUCT_DEFAULT_ITEM_TYPE,
  PRODUCT_META_TITLE_LIMIT,
  PRODUCT_META_DESCRIPTION_LIMIT,
  PLANTING_SEASON_OPTIONS,
  CLIMATE_ZONE_OPTIONS,
  SOIL_TYPE_OPTIONS,
  WATER_NEED_OPTIONS,
  SUN_EXPOSURE_OPTIONS,
  type ItemType,
  type SpecCategory,
  type PlantingSeason,
  type ClimateZone,
  type SoilType,
  type WaterNeed,
  type SunExposure,
  type ProductDetailTabKey,
  type ProductDetailFormState,
  type ProductDto,
  type ProductListQueryParams,
  type ProductCreatePayload,
  type ProductUpdatePayload,
  type ProductReorderItem,
  type ProductReorderPayload,
  type ProductImageDto,
  type ProductImageCreatePayload,
  type ProductFaqDto,
  type ProductFaqCreatePayload,
  type ProductFaqUpdatePayload,
  type ProductSpecDto,
  type ProductSpecCreatePayload,
  type ProductSpecUpdatePayload,
  type ProductReviewDto,
  type ProductReviewCreatePayload,
  type ProductReviewUpdatePayload,
  buildProductLocaleOptions,
  buildProductsListQueryParams,
  buildProductToastMessage,
  createEmptyProductDetailForm,
  formatProductPrice,
  mapProductToDetailForm,
} from "@/integrations/shared/products/index";

export {
  CUSTOM_PAGES_ADMIN_BASE,
  CUSTOM_PAGE_DEFAULT_LOCALE,
  CUSTOM_PAGE_DEFAULT_MODULE_KEY,
  type CustomPageDetailTabKey,
  type CustomPageDetailFormState,
  type CustomPageDto,
  type CustomPageListQueryParams,
  type CustomPageCreatePayload,
  type CustomPageUpdatePayload,
  type CustomPageReorderItem,
  type CustomPageReorderPayload,
  buildCustomPageLocaleOptions,
  buildCustomPagesListQueryParams,
  buildCustomPageToastMessage,
  createEmptyCustomPageDetailForm,
  mapCustomPageToDetailForm,
} from "@/integrations/shared/custom-pages/index";

export {
  SUPPORT_ADMIN_BASE,
  SUPPORT_DEFAULT_LOCALE,
  FAQ_CATEGORY_OPTIONS,
  TICKET_STATUS_OPTIONS,
  TICKET_PRIORITY_OPTIONS,
  type FaqCategory,
  type TicketStatus,
  type TicketPriority,
  type SupportFaqDto,
  type SupportFaqListQueryParams,
  type SupportFaqCreatePayload,
  type SupportFaqUpdatePayload,
  type SupportFaqReorderItem,
  type SupportFaqReorderPayload,
  type SupportTicketDto,
  type SupportTicketListQueryParams,
  type SupportTicketUpdatePayload,
  getTicketStatusVariant,
  getTicketPriorityVariant,
  buildSupportFaqsListQueryParams,
  buildSupportTicketsListQueryParams,
} from "@/integrations/shared/support/index";

export {
  GALLERY_ADMIN_BASE,
  GALLERY_DEFAULT_LOCALE,
  GALLERY_META_TITLE_LIMIT,
  GALLERY_META_DESCRIPTION_LIMIT,
  type GalleryDetailTabKey,
  type GalleryDetailFormState,
  type GalleryDto,
  type GalleryListQueryParams,
  type GalleryCreatePayload,
  type GalleryUpdatePayload,
  type GalleryReorderItem,
  type GalleryReorderPayload,
  type GalleryImageDto,
  type GalleryImageCreatePayload,
  buildGalleryLocaleOptions,
  buildGalleryListQueryParams,
  buildGalleryToastMessage,
  createEmptyGalleryDetailForm,
  mapGalleryToDetailForm,
} from "@/integrations/shared/gallery/index";

export {
  REFERENCES_ADMIN_BASE,
  REFERENCE_DEFAULT_LOCALE,
  REFERENCE_META_TITLE_LIMIT,
  REFERENCE_META_DESCRIPTION_LIMIT,
  type ReferenceDetailTabKey,
  type ReferenceDetailFormState,
  type ReferenceDto,
  type ReferenceListQueryParams,
  type ReferenceCreatePayload,
  type ReferenceUpdatePayload,
  type ReferenceReorderItem,
  type ReferenceReorderPayload,
  type ReferenceImageDto,
  type ReferenceImageCreatePayload,
  buildReferenceLocaleOptions,
  buildReferencesListQueryParams,
  buildReferenceToastMessage,
  createEmptyReferenceDetailForm,
  mapReferenceToDetailForm,
} from "@/integrations/shared/references/index";

export {
  LIBRARY_ADMIN_BASE,
  LIBRARY_DEFAULT_LOCALE,
  LIBRARY_META_TITLE_LIMIT,
  LIBRARY_META_DESCRIPTION_LIMIT,
  type LibraryDetailTabKey,
  type LibraryDetailFormState,
  type LibraryDto,
  type LibraryListQueryParams,
  type LibraryCreatePayload,
  type LibraryUpdatePayload,
  type LibraryReorderItem,
  type LibraryReorderPayload,
  type LibraryImageDto,
  type LibraryImageCreatePayload,
  type LibraryFileDto,
  type LibraryFileCreatePayload,
  type LibraryFileUpdatePayload,
  buildLibraryLocaleOptions,
  buildLibraryListQueryParams,
  buildLibraryToastMessage,
  createEmptyLibraryDetailForm,
  mapLibraryToDetailForm,
} from "@/integrations/shared/library/index";

export {
  DB_ADMIN_BASE,
  DB_ADMIN_MODULE_KEYS,
  type DbAdminModuleKey,
  type DbAdminTabKey,
  type DbImportTabKey,
  type DbModuleTabKey,
  type DbSnapshot,
  type DbSnapshotCreatePayload,
  type DbImportTextPayload,
  type DbImportUrlPayload,
  type DbModuleExportParams,
  type DbModuleImportPayload,
  type DbUiExportParams,
  type DbUiBootstrapPayload,
  type DbModuleManifestEntry,
  type DbModuleValidationResult,
  type DbOperationResult,
  formatSnapshotSize,
  formatSnapshotDate,
  buildDbModuleOptions,
} from "@/integrations/shared/db-admin/index";

export {
  POPUPS_ADMIN_BASE,
  POPUP_DEFAULT_LOCALE,
  POPUP_TYPE_OPTIONS,
  POPUP_TEXT_BEHAVIOR_OPTIONS,
  POPUP_LINK_TARGET_OPTIONS,
  POPUP_DISPLAY_FREQUENCY_OPTIONS,
  type PopupType,
  type PopupTextBehavior,
  type PopupLinkTarget,
  type PopupDisplayFrequency,
  type PopupDetailTabKey,
  type PopupDetailFormState,
  type PopupDto,
  type PopupListQueryParams,
  type PopupCreatePayload,
  type PopupUpdatePayload,
  type PopupReorderPayload,
  type PopupSetStatusPayload,
  createEmptyPopupDetailForm,
  mapPopupToDetailForm,
  buildPopupsListQueryParams,
  buildPopupToastMessage,
  parseTargetPaths,
} from "@/integrations/shared/popups/index";
