// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-locales-manifest.mjs

import locale_tr from '@/locale/tr';

export const LOCALE_MESSAGES = {
  'tr': locale_tr,
} as const;

export type LocaleCode = keyof typeof LOCALE_MESSAGES;
export const LOCALE_CODES = Object.keys(LOCALE_MESSAGES) as LocaleCode[];
